name: DynamicMTML Pack
id:   DynamicMTML
key:  dynamicmtml
author_name: Alfasado Inc.
author_link: http://alfasado.net/
pack_link: https://github.com/PowerCMS/DynamicMTML
version: 2.05
schema_version: 1.02
l10n_class: DynamicMTML::L10N
init_request: >
    sub {
        my $app = MT->instance;
        if ( ref $app ne 'MT::App::CMS' ) {
            my $ua = $app->get_header( 'User-Agent' ) || '';
            if ( $ua =~ /\ADoCoMo\/2\.0 / ) {
                $app->{ response_content_type } = 'application/xhtml+xml';
            }
        }
    }
config_settings:
    DynamicForceCompile:
        default: 0
        updatable: 1
    DisableCompilerWarnings:
        default: 0
        updatable: 1
    UserSessionTimeoutNoCheck:
        default: 0
        updatable: 1
    DynamicSiteBootstrapper:
        default: .mtview.php
        updatable: 1
    DynamicIncludeStatic:
        default: 0
        updatable: 1
    AllowMagicQuotesGPC:
        default: 0
        updatable: 1
    DynamicPHPFirst:
        default: 0
        updatable: 1
    DynamicAllowPHPinTemplate:
        default: 1
        updatable: 1
    PermCheckAtPreview:
        default: 0
        updatable: 1
    AllowableTags:
        default: <a><br><b><i><p><strong><em><img><ul><ol><li><blockquote><pre>
        updatable: 1
    DynamicCacheDriver:
    DynamicCachePrefix:
        default: dynamicmtmlcache
        updatable: 1
    DynamicCacheTTL:
        default: 7200
        updatable: 1
    DynamicCacheObjects:
        default: blog,template,category,entry
        updatable: 1
    DynamicCacheConfig:
        default: 1
    DynamicMemcachedServers:
    DynamicMemcachedCompressed:
    DynamicLoadYAML:
    DynamicContent2gzip:
    DataAPIVersion:
        default: v1
        updatable: 1
    DataAPIURL:
    DeleteFileAtPreview:
        default: 1
        updatable: 1
    PreviewServers:
    DynamicWorkerExpiration:
        default: 300
        updatable: 1
    PHPPearDir:
        updatable: 1
    DynamicInitPluginsLater:
        updatable: 1
    SmartphonePreviewAgent:
        default: Mozilla/5.0 (iPhone; CPU iPhone OS 5_1 like Mac OS X)
    DynamicMTMLLicense:
        default: GPL
        updatable: 1
object_types:
    blog:
        dynamic_mtml: boolean
        dynamic_cache: boolean
        dynamic_conditional: boolean
        search_cache: boolean
        search_conditional: boolean
        search_cache_expiration: string(25)
        dynamic_extension: string(255)
        exclude_extension: string(255)
        index_files: string(255)
applications:
    cms:
        menus:
            tools:clear_cache:
                label: Flush Dynamic Cache
                order: 1950
                mode: flush_dynamic_cache
                condition: $dynamicmtml::DynamicMTML::CMS::_dynamic_permission
                view:
                    - blog
                    - website
                    - system
        methods:
            install_dynamic_mtml: $dynamicmtml::DynamicMTML::CMS::_install_dynamic_mtml
            flush_dynamic_cache: $dynamicmtml::DynamicMTML::CMS::_flush_dynamic_cache
callbacks:
    MT::App::CMS::template_source.list_template: $dynamicmtml::DynamicMTML::Plugin::_list_template_source
    MT::App::CMS::template_param.list_template: $dynamicmtml::DynamicMTML::Plugin::_list_template_param
    MT::App::CMS::template_param.cfg_prefs: $dynamicmtml::DynamicMTML::Plugin::_cfg_prefs_param
    MT::App::CMS::template_source.cfg_prefs: $dynamicmtml::DynamicMTML::Plugin::_cfg_prefs_source
    MT::App::CMS::template_source.footer: $dynamicmtml::DynamicMTML::Plugin::_footer_source
    MT::App::CMS::template_param.edit_template: $dynamicmtml::DynamicMTML::Plugin::_edit_template_param
    build_file: $dynamicmtml::DynamicMTML::Plugin::_build_file
    build_page: $dynamicmtml::DynamicMTML::Plugin::_build_page
    build_file_filter: $dynamicmtml::DynamicMTML::Plugin::_build_file_filter
    build_dynamic: $dynamicmtml::DynamicMTML::Plugin::_build_dynamic
    cms_post_save.blog:
        - handler: $dynamicmtml::DynamicMTML::Plugin::_post_save_blog
          priority: 10
        - handler: $dynamicmtml::DynamicMTML::Plugin::_disable_dynamicmtml
          priority: 1
    cms_post_save.website:
        - handler: $dynamicmtml::DynamicMTML::Plugin::_post_save_blog
          priority: 10
        - handler: $dynamicmtml::DynamicMTML::Plugin::_disable_dynamicmtml
          priority: 1
    MT::Entry::post_save: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    MT::Entry::post_remove: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    MT::Page::post_save: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    MT::Page::post_remove: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    cms_post_save.author: $dynamicmtml::DynamicMTML::Plugin::_post_save_author
    api_post_save.author: $dynamicmtml::DynamicMTML::Plugin::_post_save_author
    cms_post_delete.author: $dynamicmtml::DynamicMTML::Plugin::_post_save_author
    MT::App::CMS::template_param.view_log: $dynamicmtml::DynamicMTML::Plugin::_view_log
    MT::App::CMS::template_param: $dynamicmtml::DynamicMTML::Plugin::_cb_tp
    MT::Config::post_save: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    MT::FileInfo::post_save: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    MT::FileInfo::post_remove: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    MT::Template::post_save: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    MT::Template::post_remove: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    MT::Category::post_save: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    MT::Category::post_remove: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    MT::Folder::post_save: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
    MT::Folder::post_remove: $dynamicmtml::DynamicMTML::Plugin::_cb_post_change
tags:
    block:
        RawMTML: $dynamicmtml::DynamicMTML::Tags::_hdlr_raw_mtml
        CommentOut: $dynamicmtml::DynamicMTML::Tags::_hdlr_comment_out
        CommentStrip: $dynamicmtml::DynamicMTML::Tags::_hdlr_comment_strip
        LoginAuthorCtx: $dynamicmtml::DynamicMTML::Tags::_hdlr_login_author_ctx
        ClientAuthorBlock: $dynamicmtml::DynamicMTML::Tags::_hdlr_login_author_ctx
        SearchEntries: $dynamicmtml::DynamicMTML::Tags::_hdlr_search_entries
        QueryLoop: $dynamicmtml::DynamicMTML::Tags::_hdlr_query_loop
        SetQueryVars: $dynamicmtml::DynamicMTML::Tags::_hdlr_set_query_vars
        QueryVars: $dynamicmtml::DynamicMTML::Tags::_hdlr_query_vars
        SplitVars: $dynamicmtml::DynamicMTML::Tags::_hdlr_splitvars
        IfLogin?: $dynamicmtml::DynamicMTML::Tags::_hdlr_if_login
        IfUserHasPermission?: $dynamicmtml::DynamicMTML::Tags::_hdlr_if_user_has_permission
        IfUserAgent?: $dynamicmtml::DynamicMTML::Tags::_hdlr_user_agent
        IfBlogDynamicCache?: $dynamicmtml::DynamicMTML::Tags::_hdlr_if_dynamic_cache
        IfBlogDynamicConditional?: $dynamicmtml::DynamicMTML::Tags::_hdlr_if_dynamic_conditional
        ReferralKeywords: $dynamicmtml::DynamicMTML::Tags::_hdlr_referralkeywords
        DynamicMTML: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamicmtml
        NonDynamicMTML: $dynamicmtml::DynamicMTML::Tags::_hdlr_nondynamicmtml
        IfBlogDynamicMTML?: $dynamicmtml::DynamicMTML::Tags::_hdlr_if_blog_dynamicmtml
        EntryCategoryBlock: $dynamicmtml::DynamicMTML::Tags::_hdlr_entry_category_block
        BuildRecurs: $dynamicmtml::DynamicMTML::Tags::_hdlr_build_recurs
        SetErrorHandler: $dynamicmtml::DynamicMTML::Tags::_hdlr_set_error
        StripTags: $dynamicmtml::DynamicMTML::Tags::_hdlr_strip_tags
        StripPHP: $dynamicmtml::DynamicMTML::Tags::_hdlr_strip_php
        BuildCache: $dynamicmtml::DynamicMTML::Tags::_hdlr_buildcache
        VarsRecurse: $dynamicmtml::DynamicMTML::Tags::_hdlr_vars_recurse
        JSON2MTML: $dynamicmtml::DynamicMTML::Tags::_hdlr_json2mtml
        SetHashVars: $dynamicmtml::GetHashVar::Tags::_hdlr_set_hash_vars
        UnsetStash: $dynamicmtml::GetHashVar::Tags::_hdlr_unset_stash
        UnsetVars: $dynamicmtml::GetHashVar::Tags::_hdlr_unset_vars
        LocalVars: $dynamicmtml::GetHashVar::Tags::_hdlr_local_vars
        YAML2Vars: $dynamicmtml::GetHashVar::Tags::_hdlr_yaml_to_vars
        LoopWithSort: $dynamicmtml::GetHashVar::Tags::_hdlr_loop_with_sort
        IfKeyExists?: $dynamicmtml::GetHashVar::Tags::_hdlr_key_exists
        IfVarExists?: $dynamicmtml::GetHashVar::Tags::_hdlr_value_exists
        IfValueExists?: $dynamicmtml::GetHashVar::Tags::_hdlr_value_exists
        IfInArray?: $dynamicmtml::GetHashVar::Tags::_hdlr_in_array
        IfNotInArray?: $dynamicmtml::GetHashVar::Tags::_hdlr_not_in_array
        IfIsInArray?: $dynamicmtml::GetHashVar::Tags::_hdlr_in_array
        IfVarIsScalar?: $dynamicmtml::GetHashVar::Tags::_hdlr_is_scalar
        IfVarIsArray?: $dynamicmtml::GetHashVar::Tags::_hdlr_is_array
        IfVarIsHash?: $dynamicmtml::GetHashVar::Tags::_hdlr_is_hash
        MBIf?: $dynamicmtml::GetHashVar::Tags::_hdlr_mb_if
        MBUnless?: $dynamicmtml::GetHashVar::Tags::_hdlr_mb_if
        MBElseIf: $dynamicmtml::GetHashVar::Tags::_hdlr_mb_if
        MBElse: $dynamicmtml::GetHashVar::Tags::_hdlr_mb_if
    function:
        ML: $dynamicmtml::DynamicMTML::Tags::_hdlr_raw_mtml_tag
        MTML: $dynamicmtml::DynamicMTML::Tags::_hdlr_raw_mtml_tag
        RawMTMLTag: $dynamicmtml::DynamicMTML::Tags::_hdlr_raw_mtml_tag
        BlogDynamicCache: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_cache
        BlogDynamicConditional: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_conditional
        BlogDynamicSearchCache: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_search_cache
        BlogDynamicSearchConditional: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_search_conditional
        BlogDynamicMTMLCache: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_search_cache
        BlogDynamicMTMLConditional: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_search_conditional
        BlogDynamicSearchCacheExpiration: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_search_cache_expiration
        BlogDynamicDirectoryIndex: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_directory_index
        BlogDynamicExtension: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_extension
        BlogDynamicExcludeExtension: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_exclude_extension
        BlogFilesMatchDirective: $dynamicmtml::DynamicMTML::Tags::_hdlr_blog_files_match_directive
        BlogFilesDirective: $dynamicmtml::DynamicMTML::Tags::_hdlr_blog_files_directive
        BlogFilesMatch: $dynamicmtml::DynamicMTML::Tags::_hdlr_blog_files_match
        CurrentArchiveURL: $dynamicmtml::DynamicMTML::Tags::_hdlr_current_archive_url
        CurrentArchiveFile: $dynamicmtml::DynamicMTML::Tags::_hdlr_current_archive_file
        TableColumnValue: $dynamicmtml::DynamicMTML::Tags::_hdlr_table_column_value
        Query: $dynamicmtml::DynamicMTML::Tags::_hdlr_query
        UserAgent: $dynamicmtml::DynamicMTML::Tags::_hdlr_user_agent
        PluginPath: $dynamicmtml::DynamicMTML::Tags::_hdlr_plugin_path
        PowerCMSFilesDir: $dynamicmtml::DynamicMTML::Tags::_hdlr_powercms_files_dir
        ReferralKeyword: $dynamicmtml::DynamicMTML::Tags::_hdlr_referralkeyword
        Trans: $dynamicmtml::DynamicMTML::Tags::_hdlr_trans
        EntryStatusInt: $dynamicmtml::DynamicMTML::Tags::_hdlr_entry_statusint
        AuthorLanguage: $dynamicmtml::DynamicMTML::Tags::_hdlr_author_language
        DynamicSiteBootstrapper: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_site_bootstrapper
        FileGetContents: $dynamicmtml::DynamicMTML::Tags::_hdlr_file_get_contents
        PluginVersion: $dynamicmtml::DynamicMTML::Tags::_hdlr_plugin_version
        Rand: $dynamicmtml::DynamicMTML::Tags::_hdlr_rand
        DataAPIProxy: $dynamicmtml::DynamicMTML::Tags::_hdlr_data_api_proxy
        Error: $dynamicmtml::DynamicMTML::Tags::_hdlr_error
        GetHashVar: $dynamicmtml::GetHashVar::Tags::_hdlr_get_hash_var
        GetHashKey: $dynamicmtml::GetHashVar::Tags::_hdlr_get_hash_key
        GetArrayVar: $dynamicmtml::GetHashVar::Tags::_hdlr_get_array_var
        GetArrayJoin: $dynamicmtml::GetHashVar::Tags::_hdlr_array_join
        GetArrayRand: $dynamicmtml::GetHashVar::Tags::_hdlr_array_rand
        GetVarDump: $dynamicmtml::GetHashVar::Tags::_hdlr_get_vardump
        SplitVar: $dynamicmtml::GetHashVar::Tags::_hdlr_split_var
        DeleteVars: $dynamicmtml::GetHashVar::Tags::_hdlr_delete_vars
        SaveVars: $dynamicmtml::GetHashVar::Tags::_hdlr_save_vars
        ResetVars: $dynamicmtml::GetHashVar::Tags::_hdlr_reset_vars
        RestoreVars: $dynamicmtml::GetHashVar::Tags::_hdlr_restore_vars
        SaveStash: $dynamicmtml::GetHashVar::Tags::_hdlr_save_stash
        ResetStash: $dynamicmtml::GetHashVar::Tags::_hdlr_reset_stash
        RestoreStash: $dynamicmtml::GetHashVar::Tags::_hdlr_restore_stash
        ArraySearch: $dynamicmtml::GetHashVar::Tags::_hdlr_array_search
        ArraySort: $dynamicmtml::GetHashVar::Tags::_hdlr_array_sort
        ArrayShuffle: $dynamicmtml::GetHashVar::Tags::_hdlr_array_shuffle
        ArrayReverse: $dynamicmtml::GetHashVar::Tags::_hdlr_array_reverse
        ArrayUnique: $dynamicmtml::GetHashVar::Tags::_hdlr_array_unique
        AppendVar: $dynamicmtml::GetHashVar::Tags::_hdlr_append_var
        Stash2Vars: $dynamicmtml::GetHashVar::Tags::_hdlr_stash_to_vars
        SubstrVar: $dynamicmtml::GetHashVar::Tags::_hdlr_substrvar
        ArrayMerge: $dynamicmtml::GetHashVar::Tags::_hdlr_array_merge
        MergeArray: $dynamicmtml::GetHashVar::Tags::_hdlr_array_merge
        HashMerge: $dynamicmtml::GetHashVar::Tags::_hdlr_hash_merge
        MergeHash: $dynamicmtml::GetHashVar::Tags::_hdlr_hash_merge
        SetPublishedEntryIds: $dynamicmtml::GetHashVar::Tags::_hdlr_set_published_entry_ids
        SetPublishedPageIds: $dynamicmtml::GetHashVar::Tags::_hdlr_set_published_entry_ids
        USleep: $dynamicmtml::GetHashVar::Tags::_hdlr_usleep
        MBSetVar: $dynamicmtml::GetHashVar::Tags::_hdlr_mb_set_var
        MBVar: $dynamicmtml::GetHashVar::Tags::_hdlr_mb_get_var
        MBGetVar: $dynamicmtml::GetHashVar::Tags::_hdlr_mb_get_var
    modifier:
        pickup_extension: $dynamicmtml::DynamicMTML::Tags::_filter_pickup_extension
        highlightingsearchword: $dynamicmtml::DynamicMTML::Tags::_filter_highlightingsearchword
        build_mtml: $dynamicmtml::DynamicMTML::Tags::_filter_build_mtml
        make_seo_basename: $dynamicmtml::DynamicMTML::Tags::_filter_make_seo_basename
        intval: $dynamicmtml::DynamicMTML::Tags::_filter_intval
        trimwhitespace: $dynamicmtml::DynamicMTML::Tags::_filter_trimwhitespace
        json2vars: $dynamicmtml::GetHashVar::Tags::_filter_json2vars
        vars2json: $dynamicmtml::GetHashVar::Tags::_filter_vars2json
        mtignore: $dynamicmtml::GetHashVar::Tags::_filter_mtignore
        note: $dynamicmtml::GetHashVar::Tags::_filter_note
        ts_format: $dynamicmtml::GetHashVar::Tags::_filter_ts_format
        db2ts: $dynamicmtml::GetHashVar::Tags::_filter_db2ts
    filters:
        Entries:
            entry_ids:
                handler: $dynamicmtml::GetHashVar::Tags::_hdlr_entries_entry_ids
tasks:
    FlushPageCache:
        label: Removes old page cache.
        code: $dynamicmtml::DynamicMTML::Cache::_task_flush_page_cache
        frequency: 1800
